name: "Github Actions Rabbitmq"
author: "Matheus Costa"
description: "Rabbitmq integration github actions by passwords"
inputs:
  OBJECT:
    description: "Object to send."
    required: true
  PASSWORD_VAULT_URL:
    description: "Password vault url."
    required: false
  QUEUE:
    description: "The name of the queue you are sending to."
    required: true
  RABBITMQ_HOST:
    description: "RabbitMQ host name"
    required: true
  RABBITMQ_PORT:
    description: "RabbitMQ port."
    required: true
  RABBITMQ_USER:
    description: "RabbitMQ username."
    required: true
  RABBITMQ_PASS:
    description: "RabbitMQ password."
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  color: "orange"
  icon: "message-circle"
